### ISSUE TITLE
Main build broken: previewPDF passed straight to onClick after #2401

### ISSUE THREAD

**Issue by mattssonn** [erp-mafia/gnubok#2402]
## Original report

Some checks were not successful on the push to main after #2401:

- Build and Push Docker Image / Build linux/arm64: failing after 3m
- Vercel: deployment dpl_3vSjzUbsb653gizAjzB86qDHAzdk failed
- Build and Push Docker Image / Build linux/amd64: cancelled
- Merge, sign and scan: skipped

"Build is failing. Something wrong."

## Source

Emil, GitHub checks on main at 4e8d649 (2026-09-08).

## Finding

`next build` fails type-checking on `app/(dashboard)/invoices/[id]/page.tsx:1781`:

```
error TS2322: Type '(options?: { asDraft?: boolean } | undefined) => void' is not assignable to type 'MouseEventHandler<HTMLButtonElement>'.
```

The review-pass commit de71ebda5 on #2401 gave `previewPDF` an `options` parameter but left `onClick={previewPDF}`, so React now passes the click event as `options`. The PR was merged at 23:10:15, seven seconds after that commit, before Core Build / Checks / Vercel had run on it; all four later failed on the PR too. The `protect-main` ruleset requires a PR, linear history and signatures but no status checks, so GitHub did not block the merge.

**Comment by mattssonn** [comment]
```
VERDICT   REAL: `next build` on main fails TS2322 at app/(dashboard)/invoices/[id]/page.tsx:1781, review commit de71ebda5 gave previewPDF an options arg but left onClick={previewPDF}
WHAT      Wrap it as onClick={() => previewPDF()} so the click event no longer lands in options; no behaviour change.
WHY       Every push to main since 4e8d649 is undeployable: Vercel prod and both Docker images fail, so #2401 and anything after it cannot reach users.
RISK      LOW: one JSX line, no ledger/VAT/payroll/migrations.
TESTED    npm run check:types (ratchet flagged this file), npx vitest run app/api/invoices, and the PR's own Core Build + Vercel preview must be green before merge this time.
ROLLBACK  Revert the one-line commit.
```
Considered and rejected:
- Revert #2401 entirely: the feature is sound, only the review-pass commit broke the type; a one-line fix is smaller.
- Make onClick handlers on this page all use explicit arrow wrappers: drive-by, out of scope.
- Require Core Build + Checks in the `protect-main` ruleset so a merge before CI has reported is refused by GitHub: the class fix, but it is a repo setting, Emil's call (the merge landed 7 s after the last commit, before CI ran).

**Comment by mattssonn** [comment]
Fixed on main by #2403 (25b969183) before this card was approved; main is green again at 7448490fb. Closing as duplicate. The class fix (require Core Build + Checks in the protect-main ruleset) remains Emil's call.
